### ISSUE TITLE
Library make the app crash

### ISSUE THREAD

**Issue by rdhox** [MetaLabs-inc/react-native-vimeo-iframe#1]
Have an error with the library when app start (with expo, but should be ok):

`impossible to find ./template folder`

any suggestions? 

thanks!

**Comment by Marcoo09** [comment]
Hey! I'm going to check and give you an update in the following days.

Anyway I want to tell you we discover that we can use [react-native-video](https://github.com/react-native-video/react-native-video) to display own videos of Vimeo , that is you have to have access to the vimeo account that uploads the videos..

If this is not the case and you want to use any video published by vimeo I think that this solution is good for you (when we solve this problem).

**Comment by rdhox** [comment]
Unfortunately I need to read any video on vimeo so this library can be the solution!
Thanks for your answer !

**Comment by rodrigogaraujo** [comment]
Any solution for this?
Same here :(

**Comment by Marcoo09** [comment]
Hi @rdhox @rodrigogaraujo sorry for the delay but I still couldn't attack this problem, I'm with other deadlines. 
As soon as I have time I will help you guys with that.

**Comment by dfabreguette-ap** [comment]
👍

**Comment by Marcoo09** [comment]
Hi guys, sorry for the delay. 

In the version 1.0.1 published today should be fixed the problems. Please let me know.

**Comment by Marcoo09** [comment]
@Lexe003 

1. You need to have a vimeo account and videos published in this account.
2. You need to go to your video -> Advanced Settings -> Distribution  -> Video file links -> and copy one of the links that you want to be used by react-native-video:

![image](https://user-images.githubusercontent.com/18408823/120897841-82196700-c5fe-11eb-97f7-b5bdcc365bd2.png)
