### ISSUE TITLE
Autoplay seems doesn't work

### ISSUE THREAD

**Issue by xchwarze** [MetaLabs-inc/react-native-vimeo-iframe#11]
Autoplay functionality seems to be broken 
In addition to this dependency, I am using react-native-youtube-iframe and with this the autoplay works as expected

**Comment by Marcoo09** [comment]
Hi @xchwarze, the problem was related chrome policies that not allow autoplay videos if they're not muted.
I'm going to include this fix you done improved checking the platform in which the user are in a following pr because this problem not occurs in an ios device.
