### ISSUE TITLE
Example project cannot be run

### ISSUE THREAD

**Issue by jfbn** [MetaLabs-inc/react-native-vimeo-iframe#17]
Trying to run the example project with:

1. `npm install`
2. `npm run android`

Will throw the error:
`> Project with path ':react-native-webview' could not be found in project ':app'.`

It seems the webview is not properly configured for the example project(?)

**Comment by douglasrosa0110** [comment]
https://github.com/conquer-plus/react-native-vimeo-iframe

**Comment by felipe-najson** [comment]
Hey, @jfbn we will be publishing the new version (1.1.0) of the library these days that solves this issue.

Regards, Philip
