### ISSUE TITLE
Vimeo controls overlap native iOS controls

### ISSUE THREAD

**Issue by gastondisacco** [MetaLabs-inc/react-native-vimeo-iframe#18]
Hi! Thanks for the component!

I'm testing it on iOS 15.0.2, I'm unable to use native iOS video controls after resizing back to original video player (from full screen to component size).

I see Vimeo original video controls overlaps native ones, Vimeo is the one working. I can't find a solution like hiding Vimeo ones but allowing native to work, or hide native and keep using Vimeo controls.

<img width="414" alt="Screen Shot 2021-11-10 at 10 05 17" src="https://user-images.githubusercontent.com/6180245/141118868-ba9cbb84-58bc-49ae-8061-9e603663399e.png">

Thanks so much.

**Comment by cuongid** [comment]
Same issues. Did you find solution for this @gastondisacco

**Comment by kevinmeyvaert** [comment]
Can you please reopen this issue as this still happens on 1.1.0
