### ISSUE TITLE
Media controls looks quite small for mobile screens

### ISSUE THREAD

**Issue by deltasamantha** [MetaLabs-inc/react-native-vimeo-iframe#20]
## Description
When rendering video player, the initial media controls (play button, pause button etc.) looks quite small for mobile screen. I didn't find a configurations or styling workaround for solving this. Is there a way of styling or some how increase sizes of the media controls.

## Screenshot
![IMG_8222](https://user-images.githubusercontent.com/6166645/147621939-e74d7af8-d620-4e44-b311-95a75b4134d5.PNG)

**Comment by douglasrosa0110** [comment]
https://github.com/MetaLabs-inc/react-native-vimeo-iframe/pull/22

**Comment by douglasrosa0110** [comment]
https://github.com/conquer-plus/react-native-vimeo-iframe

**Comment by GCnomore** [comment]
const INJECTEDJAVASCRIPT =
    "const meta = document.createElement('meta'); meta.setAttribute('content', 'width=device-width, initial-scale=1, maximum-scale=0.99, user-scalable=0'); meta.setAttribute('name', 'viewport'); document.getElementsByTagName('head')[0].appendChild(meta); const injectedJavascript = `(function() { window.postMessage = function(data) {window.eactNativeWebView.postMessage(data);};})()`";

**Comment by narendrachettri** [comment]
Have you solved this problem @deltasamantha ? if Yes, can you guide me?

**Comment by felipe-najson** [comment]
Hey, @deltasamantha @narendrachettri  @GCnomore we will be publishing the new version (1.1.0) of the library these days that solves this issue.

Regards, Philip
