### ISSUE TITLE
New query param required in vimeo url.

### ISSUE THREAD

**Issue by dragosheroiu95** [MetaLabs-inc/react-native-vimeo-iframe#21]
Hello. I need to pass a new parameter to the url, some sort of security token. I have an url like https://player.vimeo.com/video/${id}?h=${token}.

Thanks.

**Comment by douglasrosa0110** [comment]
https://www.npmjs.com/package/@conquerplus/react-native-web-video

**Comment by felipe-najson** [comment]
Hey, @jfbn we will be publishing the new version (1.1.0) of the library these days that add this feature.

Regards, Philip
