### ISSUE TITLE
Implement requestFullscreen method & callback

### ISSUE THREAD

**Issue by ssanju01** [MetaLabs-inc/react-native-vimeo-iframe#25]
Hi,
The current implementation works fine but fullscreen does not rotate video to landscape, if we implement requestFullscreen method callback then the developer can force the app to rotate to landscape mode.

**Comment by felipe-najson** [comment]
Hey, @ssanju01 thank you for reporting this, we will be publishing the new version of the library these days with the fullScreen landscape mode.

Regards, Philip
