### ISSUE TITLE
Froogaloop.js  does not load sometimes

### ISSUE THREAD

**Issue by zeusstl** [MetaLabs-inc/react-native-vimeo-iframe#26]
There are some physical locations in which the froogaloop script does not load for me:
https://f.vimeocdn.com/js/froogaloop2.min.js

This could be due to black list ip address or some other reason like that.
Or perhaps there is some variable missing in the implementation similar to how this is due to missing a required variable:
https://vimeo.zendesk.com/hc/en-us/articles/4409305565069-Embedded-player-displays-This-video-does-not-exist-message

I am trying to hardcode the entire froogaloop script into a patch for now, but it is not working, yet.

Has anyone experienced anything similar with the iframe?

(This may relate to this issue: https://github.com/MetaLabs-inc/react-native-vimeo-iframe/issues/19 )

**Comment by Marcoo09** [comment]
Hey, @zeusstl we will be publishing the new version (1.1.0) of the library these days.

In this version we're not going to use Froogaloop anymore. Let us know if you experience this bug again.

Regards, 
Marco
