### ISSUE TITLE
library  issue 

### ISSUE THREAD

**Issue by shahzaibali-code** [MetaLabs-inc/react-native-vimeo-iframe#3]
\node_modules\react-native-vimeo-iframe\src\template\index.ts: Did not expect a type annotation here. (2:9)

  1 | export default webplayer (
> 2 |   videoId: string,    this take problem
    |          ^
  3 |   loop: boolean,
  4 |   autoPlay: boolean,
  5 |   controls: boolean,

firstly  not include ./template and type.ts   first error 
if run but video not play 
what the exist issue ,can you identify then

**Comment by IgorCSilva** [comment]
Same problem here**!**

**Comment by Marcoo09** [comment]
Fixed on #7
