### ISSUE TITLE
Is it possible to start a video programatically?

### ISSUE THREAD

**Issue by MoSattler** [MetaLabs-inc/react-native-vimeo-iframe#37]
Is there a way to start a video programatically? I tried to access the player with [`getVimeoPlayer`](https://github.com/MetaLabs-inc/react-native-vimeo-iframe/blob/main/src/types.ts#L14), but it doesn't seem to work.

**Comment by Marcoo09** [comment]
@MoSattler currently not, we'll work on that on following weeks.

**Comment by Marcoo09** [comment]
Hi @MoSattler, currently you can put an auto play flag on the `params` prop: `&autoplay=1`
<img width="262" alt="image" src="https://user-images.githubusercontent.com/18408823/187046424-96b69524-7cd4-46f5-b0ce-f6861510158c.png">
What you can do is play with this prop on you app and when you want to trigger the play of the player change the params sent to the video.

**Comment by MoSattler** [comment]
@Marcoo09 Wouldn't that reload the whole web view?

**Comment by 7assenTlili** [comment]
@Marcoo09 changing the params prop to have '&autoplay=1' throws the following warning: Changes to property mediaPlaybackRequiresUserAction do nothing after initial render
