### ISSUE TITLE
On ios video always open if full-screen

### ISSUE THREAD

**Issue by ProjectKarol** [MetaLabs-inc/react-native-vimeo-iframe#38]
I spend a couple of days tracking this issue.  And I didn't find the answer.
Looking for help. 
Why on IOS videos always play in full-screen mode,  On android is ok. 
I use simple code from examples. 
These are my dependencies:
```
   "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "react": "17.0.2",
    "react-native": "0.68.1",
    "react-native-gesture-handler": "^2.4.1",
    "react-native-pager-view": "^5.4.24",
    "react-native-paper": "^4.12.1",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-vimeo-iframe": "^1.1.1",
    "react-native-webview": "^11.18.2",
    "styled-components": "^5.3.5"
  },
```

**Comment by shrekuu** [comment]
@ProjectKarol  For WebView, we need to pass: `allowsInlineMediaPlayback="true"` to WebView component to make the video play inline by default.
Currently we do not have this option to pass into inner WebView component I believe. 

It's difficult for me to contribute to a optional prop to this repo. You man try WebView. The URI is the "src" attribute value from the embedded code.

```jsx
<WebView
  allowsInlineMediaPlayback="true"
  source={{
    uri: 'https://player.vimeo.com/video/745502766?h=a4e4fbef0c',
  }}
/>
```

**Comment by Marcoo09** [comment]
Hi @shrekuu @ProjectKarol , on `otherProps` prop you can specify webview props.
