### ISSUE TITLE
loadedmetadata prop not working ? 

### ISSUE THREAD

**Issue by Anudnya93** [MetaLabs-inc/react-native-vimeo-iframe#43]
I have tried using loadedmetadata inside the handlers props. But there aren't any logs getting printed. Kindly help.

const videoCallbacks = {
timeupdate: data => console.log('timeupdate: ', data),
play: data => console.log('play: ', data),
pause: data => console.log('pause: ', data),
fullscreenchange: data => console.log('fullscreenchange: ', data),
ended: data => console.log('ended: ', data),
controlschange: data => console.log('controlschange: ', data),
loadedmetadata: data => console.log('loadedmetadata', data),
loadeddata: data => console.log('loadeddata', data)
}

return (
<Vimeo
videoId={'741193833'}
params={'api=1&autoplay=0'}
={videoCallbacks}
containerStyle={{
height: 150,
width: '100%'
}}
otherProps={{ allowsInlineMediaPlayback: true }}
/>
)

**Comment by Marcoo09** [comment]
Hi @Anudnya93, I will be looking this in the following days

**Comment by agustin-ferrari** [comment]
> Hi @Anudnya93, I will be looking this in the following days

Have you been able to see this issue? Is there any other way I can check whether the video is ready to play?
Thanks in advance

**Comment by Marcoo09** [comment]
Hi @Anudnya93. I was trying to reproduce the problem without success. I'm attaching a screenshot.
<img width="352" alt="image" src="https://user-images.githubusercontent.com/18408823/226147917-64075638-4a65-4592-acb5-fde470314ab6.png">

**Comment by Anudnya93** [comment]
Hi @Marcoo09. I was expecting to have video info in the metadata such as height, width, aspectratio etc.

**Comment by Marcoo09** [comment]
Hi @Anudnya93. I was checking to add more information but it's in charge of the player to return this data. Maybe you can try with the [api](https://developer.vimeo.com/api/reference/videos#get_video) from video to get the information.
