### ISSUE TITLE
[Critical] New videos don't play on iOS

### ISSUE THREAD

**Issue by zeusstl** [MetaLabs-inc/react-native-vimeo-iframe#44]
Something changed and new videos don't work anymore on iOS in this package. The error comes from the vimeo side.

I am testing on:
iOS: 15.2
Device: any (including xcode simulators)

<img width="615" alt="Screen Shot 2022-11-06 at 12 59 47 PM" src="https://user-images.githubusercontent.com/5577624/200187131-ffc9005d-8fdf-42fa-a3c6-e7bf87b9538a.png">

Have tried uploading different video formats to vimeo and the same happens every time.

Sidenote: The same videos work in a desktop browser with the js vimeo player link and even in the Safari developer simulators on the desktop Safari.

It is making it impossible to use vimeo with this package. Has anyone else experienced this?

**Comment by Marcoo09** [comment]
Hi @zeusstl sorry for the late reply. This problem was fixed in the last version. Let me know if the problem was fixed, if not please share with me a public video to test on my computer and your react native version
