### ISSUE TITLE
Can we customize player buttons?

### ISSUE THREAD

**Issue by ZeeshanRopstam** [MetaLabs-inc/react-native-vimeo-iframe#46]
Can we customize play button,progress bar and timer.

**Comment by Marcoo09** [comment]
Hi @sash20m. Let me know if you want to have a meeting to discuss these changes to replicate them in this library.

**Comment by sash20m** [comment]
> Hi @sash20m. Let me know if you want to have a meeting to discuss these changes to replicate them in this library.

Hi. Sure, I am still adding things here and there. I'll make a fork somewhere in the future when I know the version is fully stable.

**Comment by Marcoo09** [comment]
Hi @sash20m, feel free to open a pr or share the changes you want to do on the library to contemplate the custom player button
