### ISSUE TITLE
vimeo player crashing the android app

### ISSUE THREAD

**Issue by Devshail** [MetaLabs-inc/react-native-vimeo-iframe#47]
Hi, I am having an issue with a library called react-native-vimeo-iframe. The problem is that when i am rendering video in android the app got crashed i am getting an error message in logcat of the android studio which is =>
 2022-12-06 14:09:19.465 11998-12078/com.dyreid A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 12078 (RenderThread), pid 11998 (com.dyreid). 

**react-native-info**

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 30.71 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/Documents/Projects/dyreid/node_modules/.bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.5.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 29, 30, 31, 32
      Build Tools: 30.0.1, 30.0.2, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: 0.66.4

On other hand the IOS working perfectly. I am adding the code snippet which I am using to render the video 

```
<View style={{flex:1}}>
 <Vimeo style={{height:Dimensions.get('window').width-100,}}
  videoId={idVideo[1]} // here is the video id which I am getting from the server
  handlers={videoCallbacks}/>
</View>
```

**Comment by Anudnya93** [comment]
I am also exact crash on android. @Devshail were you able to resolve it ?

**Comment by Marcoo09** [comment]
Hi @Devshail @Anudnya93 
I'll check the bug this week

**Comment by stefano-vergani** [comment]
Hi, any update on this?

**Comment by kevinmeyvaert** [comment]
Hi guys! I've had a similar crash. When the Vimeo component is rendered inside a list (tested with ScrollView), and the user overscrolls this list, the app crashes.

You can work around this by disabling overscroll: `<ScrollView overScrollMode="never">`.

**Comment by Marcoo09** [comment]
Hi @kevinmeyvaert 
Does this happen with scrollview from react native? I'm trying to reproduce it without success.

**Comment by kevinmeyvaert** [comment]
@Marcoo09 indeed. But I only have the crash in simulators, not on physical android devices.

**Comment by Marcoo09** [comment]
Thanks @kevinmeyvaert 
I was able to reproduce the problem but I didn't find any fix to make on this library given it's a problem related react-native-webview as you can see in the following [issue](https://github.com/react-native-webview/react-native-webview/issues/2364)
The problem as mentioned there occurs when you scroll until the end.

I'll keep and eye on this issue to see if there is sth else I could do and by the moment I'll add in the Readme this workaround
