### ISSUE TITLE
[1.0.1]v Error: Unable to resolve module ./template  

### ISSUE THREAD

**Issue by Waqas-Jani** [MetaLabs-inc/react-native-vimeo-iframe#5]
Hi, i try to use this lib, and follow the instruction and aslo see example folder in repo. 
but i try to use in my code, then i facing this issue.
Unable to find  "import webplayer from './template'

When i found  lib in node_modules, and i didn't find any file name,  ./template

Please help me to fix

**Comment by jbeck018** [comment]
I had the same issue @Waqas-Jani. 

If you change:
import webplayer from './template'
import { LayoutProps } from './types'

to: 
import webplayer from '../lib/template'
import { LayoutProps } from '../lib/types'

it'll fix the issue.

**Comment by Marcoo09** [comment]
Fixed on #7
