### ISSUE TITLE
Crashing on iOS: "RNCWebView" was not found in the UIManager

### ISSUE THREAD

**Issue by Aichnerc** [MetaLabs-inc/react-native-vimeo-iframe#51]
I get the **critical** error `requireNativeComponent: "RNCWebView" was not found in the UIManager.` on **iOS**.

I use the **managed Expo workflow**, so I am not able to run `react-native link`. I have followed the [Expo guideline](https://docs.expo.dev/versions/latest/sdk/webview/) for installing `react-native-webview`.

**Comment by Marcoo09** [comment]
Hi @Aichnerc. It's not necessary to install react-native-webview into the project. How was you installing react-native-vimeo-iframe?
I tried doing "npx expo install react-native-vimeo-iframe" as explained [here](https://docs.expo.dev/workflow/using-libraries/) and it works properly. 
If this does not work please share a reproducable snack to test it on my end
