### ISSUE TITLE
iOS video in playing only in full screen

### ISSUE THREAD

**Issue by ChamithaCalcey** [MetaLabs-inc/react-native-vimeo-iframe#52]
in iOS video is playing only in full-screen mode. Is there any way to play the video within the iframe?

**Comment by sato-daiki** [comment]
@ChamithaCalcey
Hi. This is WebView problem.

You should add  
bounces={false}

I can work it.

**Comment by sato-daiki** [comment]
You should add this!
> allowsInlineMediaPlayback

I can work on it!

**Comment by ChamithaCalcey** [comment]
Thanks! It works now
