### ISSUE TITLE
how to increase player height?

### ISSUE THREAD

**Issue by harshinventory** [MetaLabs-inc/react-native-vimeo-iframe#55]
Hi there,
              I am integrating this library and I am showing this player in the center of the screen, But as my requirement, I can't increase the size of the player as it is always the same height. Please let me know how can I do this?

**Comment by Marcoo09** [comment]
Hi @harshinventory, with increasing you mean to fill the whole screen?
<img width="376" alt="image" src="https://user-images.githubusercontent.com/18408823/227743841-0673878e-85b0-453e-88df-0dd493093c99.png">
In this case you can use the parameter autoplay to as soon it's rendered it start to play and fill the whole screen.
`<Vimeo
            videoId={'712158996'}
            handlers={videoCallbacks}
            params={'autoplay=1'}
          />`

Let me know if this answer your question or pls give more context/an example about what you need to do.

**Comment by harshinventory** [comment]
![simulator_screenshot_A58E8ECC-58B7-4520-AE7C-18E3F79C8247](https://user-images.githubusercontent.com/87113814/227848087-c5306f08-1e0e-4bd8-9ff0-3bd79b81dc73.png)


Hello, @Marcoo09 !!

As you can see in the screenshot, I'm showing the player on this screen; this is not the full-screen view of the player.
Please ignore the white background the red line border square is my component for the player. And for the arrow, you can see I want to increase the size in that direction without a full screen. I hope It's clear my requirement. I really appreciate any help you can provide.

**Comment by Marcoo09** [comment]
Hi @harshinventory. Thanks for the detailed information!
You can see the params that could be used to change the setup of the player [here](https://developer.vimeo.com/player/sdk/embed) 
As I mentioned you can use the autoplay to inmeditaely open the full screen mode, I was checking and I didn't see any param to show in full screen in every scenario.
Regarding the height, If the video is rectangular, it will look small both minimized and in full screen. Maybe you can force this screen to change the orientation and run as landscape.
