### ISSUE TITLE
IOS white screen

### ISSUE THREAD

**Issue by dels1in** [MetaLabs-inc/react-native-vimeo-iframe#64]
Trying to play a video on iOS 16.4 simulator returns a white screen

![Captura de Tela 2023-05-17 às 16 20 15](https://github.com/MetaLabs-inc/react-native-vimeo-iframe/assets/47418329/32c33e41-cac6-4d5f-b1ee-9078d27038d4)

made it work after changing the video quality, but doesn't work on the first time loading the video(tried with and without autoplay, same result)

UI works and still tracks video progress, audio is also ok, just the image is not showing

Also tried in another iOS version(16.0) and worked fine. Apparently, the problem is only on the new iOS version 

Works fine on Android

"react-native-vimeo-iframe": "^1.2.1",
"react": "17.0.2",
"react-native": "0.66.5",

**Comment by l3aconator** [comment]
same story here with same version numbers

**Comment by luizfonsecaa** [comment]
Same error with this versions:
"react-native-vimeo-iframe": "^1.2.1",
"react": "18.1.0",
"react-native": "0.70.8",

**Comment by kushalAppiness** [comment]
javaScriptEnabled={true}
                    allowsFullscreenVideo={false}
                    allowsInlineMediaPlayback
                    injectedJavaScript='
                    document.body.style.backgroundColor = "black";
                    true;
                    '
                    
                    try this props

**Comment by Shasikhan** [comment]
Same issue. Did anyone found a solution?

**Comment by aguilanegra** [comment]
Same here, if there is a solution, I'm very interested.

**Comment by Marcoo09** [comment]
Hi all, as detailed [here](https://github.com/MetaLabs-inc/react-native-vimeo-iframe/issues/50) and [here](https://github.com/vimeo/player.js/issues/919), this issue does not happen on real devices and in the latest iOS versions. Closing the bug, as it's not directly related to this library. I'll monitor the player SDK for any potential workarounds or fixes.
